### ISSUE TITLE
path.existsSync is now called `fs.existsSync`.

### ISSUE THREAD

**Issue by ghost** [lexandera/Aardwolf#12]
I get this error trying to run it:

node app.js -h 192.168.1.13
path.existsSync is now called `fs.existsSync`.

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: listen EADDRINUSE
    at errnoException (net.js:770:11)
    at Server._listen2 (net.js:910:14)
    at listen (net.js:937:10)
    at Server.listen (net.js:994:9)
    at dns.js:72:18
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

Help?

Update?

Also why not make it a npm install? I'd be glad to help.

**Comment by martin-naumann** [comment]
I think your actual error is the EADDRINUSE, which means either port 8000 or 8500 is used by another process.
